name: boston-heat-vulnerability
channels:
  - conda-forge
dependencies:
  - python=3.*
  - ipython=7.10.*
  - jupyterlab=3.*
  - numpy
  - pandas
  - shapely
  - geopandas
  - geopy
  - matplotlib
  - mapclassify
  - contextily
  - folium
  - rasterio
  - rasterstats